//! Cross-validation tests for CLI and basis_core signatures
//!
//! These tests verify that signatures generated by the CLI crypto module
//! are compatible with the basis_core SchnorrVerifier, and vice versa.
//! This ensures consistency across the codebase.

use crate::schnorr;
use crate::schnorr_test_vectors::SCHNORR_TEST_VECTORS;

#[cfg(test)]
mod tests {
    use super::*;

    /// Test that basis_store signatures verify with basis_core verifier
    #[test]
    fn test_basis_store_signatures_verify_with_basis_core() {
        for vector in SCHNORR_TEST_VECTORS.iter().filter(|v| v.should_verify) {
            let issuer_pubkey: [u8; 33] = hex::decode(vector.issuer_pubkey_hex)
                .expect("Invalid issuer pubkey hex")
                .try_into()
                .expect("Issuer pubkey must be 33 bytes");
            let message = hex::decode(vector.message_hex)
                .expect("Invalid message hex");
            let signature: [u8; 65] = hex::decode(vector.signature_hex)
                .expect("Invalid signature hex")
                .try_into()
                .expect("Signature must be 65 bytes");

            // Verify with basis_core::impls::SchnorrVerifier
            let verifier = basis_core::impls::SchnorrVerifier;
            let result = basis_core::traits::SignatureVerifier::verify_signature(
                &verifier, &signature, &message, &issuer_pubkey
            );
            
            assert!(
                result.is_ok(),
                "Test vector {}: basis_core verifier should accept basis_store test vector signature",
                vector.id
            );
        }
    }

    /// Test that all test vectors with should_verify=true have z.bitLength <= 255
    /// This validates our test vectors match the Scala constraint
    #[test]
    fn test_test_vectors_bitlength_constraint() {
        for vector in SCHNORR_TEST_VECTORS.iter().filter(|v| v.should_verify) {
            let signature = hex::decode(vector.signature_hex)
                .expect("Invalid signature hex");
            
            // Extract z from signature (last 32 bytes)
            let z_bytes: [u8; 32] = signature[33..65]
                .try_into()
                .expect("Signature must be at least 65 bytes");
            
            let z_big = num_bigint::BigUint::from_bytes_be(&z_bytes);
            let bit_length = z_big.bits();
            
            assert!(
                bit_length <= 255,
                "Test vector {}: z.bitLength = {} > 255. Signatures with bitLength > 255 are rejected by Scala/contract.",
                vector.id,
                bit_length
            );
        }
    }

    /// Test that invalid test vectors (should_verify=false) fail verification
    #[test]
    fn test_invalid_vectors_fail_verification() {
        for vector in SCHNORR_TEST_VECTORS.iter().filter(|v| !v.should_verify) {
            let issuer_pubkey: [u8; 33] = hex::decode(vector.issuer_pubkey_hex)
                .expect("Invalid issuer pubkey hex")
                .try_into()
                .expect("Issuer pubkey must be 33 bytes");
            let message = hex::decode(vector.message_hex)
                .expect("Invalid message hex");
            let signature: [u8; 65] = hex::decode(vector.signature_hex)
                .expect("Invalid signature hex")
                .try_into()
                .expect("Signature must be 65 bytes");

            // Verify with basis_store
            let result = schnorr::schnorr_verify(&signature, &message, &issuer_pubkey);
            
            assert!(
                result.is_err(),
                "Test vector {}: Invalid signature should fail verification",
                vector.id
            );
        }
    }
}
