//! Redemption flow for Basis offchain notes

use thiserror::Error;

use crate::transaction_builder::{RedemptionTransactionBuilder, TxContext};
use crate::{blake2b256_hash, IouNote, NoteError, PubKey, TrackerStateManager};

#[derive(Error, Debug)]
pub enum RedemptionError {
    #[error("Note not found")]
    NoteNotFound,
    #[error("Invalid note signature")]
    InvalidNoteSignature,
    #[error("Redemption too early: {0} < {1}")]
    RedemptionTooEarly(u64, u64),
    #[error("Insufficient collateral: {0} < {1}")]
    InsufficientCollateral(u64, u64),
    #[error("Reserve not found: {0}")]
    ReserveNotFound(String),
    #[error("Transaction building error: {0}")]
    TransactionError(String),
    #[error("Storage error: {0}")]
    StorageError(String),
    #[error("Invalid public key: {0}")]
    InvalidPublicKey(String),
}

impl From<NoteError> for RedemptionError {
    fn from(err: NoteError) -> Self {
        match err {
            NoteError::InvalidSignature => RedemptionError::InvalidNoteSignature,
            NoteError::FutureTimestamp => {
                RedemptionError::StorageError("Future timestamp".to_string())
            }
            NoteError::PastTimestamp => RedemptionError::StorageError("Past timestamp".to_string()),
            NoteError::RedemptionTooEarly => RedemptionError::RedemptionTooEarly(0, 0),
            NoteError::StorageError(msg) => RedemptionError::StorageError(msg),
            _ => RedemptionError::StorageError(format!("{:?}", err)),
        }
    }
}

/// Redemption request parameters
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RedemptionRequest {
    /// Issuer's public key (hex encoded)
    pub issuer_pubkey: String,
    /// Recipient's public key (hex encoded)
    pub recipient_pubkey: String,
    /// Amount to redeem
    pub amount: u64,
    /// Timestamp of the note being redeemed
    pub timestamp: u64,
    /// Reserve contract box ID (hex encoded)
    pub reserve_box_id: String,
    /// Tracker box ID (hex encoded) - fetched from blockchain
    pub tracker_box_id: String,
    /// Tracker NFT ID from reserve box R6 register (hex encoded, 64 chars = 32 bytes)
    pub tracker_nft_id: String,
    /// Current blockchain height - fetched from Ergo node
    pub current_height: u64, // Stored as u64 from API, converted to u32 for transaction builder
    /// Recipient's address for redemption output
    pub recipient_address: String,
    /// Change address for transaction outputs (derived from tracker pubkey if not specified)
    pub change_address: String,
    /// Issuer's Schnorr signature (65 bytes, hex encoded = 130 chars)
    /// Signs: key || totalDebt || timestamp (48 bytes)
    /// where key = blake2b256(ownerKey || receiverKey)
    pub issuer_signature: String,
    /// Whether this is an emergency redemption (after 3 days tracker unavailability)
    #[serde(default)]
    pub emergency: bool,
    /// Tracker's Schnorr signature (65 bytes, hex encoded = 130 chars)
    /// Optional: will be generated by server if not provided for normal redemption
    #[serde(default)]
    pub tracker_signature: Option<String>,
    /// Value of the reserve box being spent (in nanoERG)
    /// Fetched from the blockchain by the API layer
    pub reserve_box_value: u64,
    /// Optional wallet-owned fee input box IDs. When empty, the redemption manager
    /// will use a placeholder fee input in test/offline mode.
    #[serde(default)]
    pub fee_input_box_ids: Vec<String>,
    /// Total value provided by the fee input boxes. Must be >= the required fee.
    #[serde(default)]
    pub fee_input_total_value: u64,
}

/// Redemption proof and transaction data
#[derive(Debug, Clone)]
pub struct RedemptionData {
    /// Unique redemption ID
    pub redemption_id: String,
    /// The note being redeemed
    pub note: IouNote,
    /// AVL tree proof for the note
    pub avl_proof: Vec<u8>,
    /// Redemption transaction bytes (hex encoded)
    pub transaction_bytes: String,
    /// Required signatures for the transaction
    pub required_signatures: Vec<String>,
    /// Estimated transaction fee
    pub estimated_fee: u64,
    /// Timestamp when redemption can be executed
    pub redemption_time: u64,
}

/// Redemption manager for handling note redemptions
pub struct RedemptionManager {
    pub tracker: TrackerStateManager,
}

impl RedemptionManager {
    /// Create a new redemption manager
    pub fn new(tracker: TrackerStateManager) -> Self {
        Self { tracker }
    }

    /// Initiate redemption process for a note
    pub fn initiate_redemption(
        &mut self,
        request: &RedemptionRequest,
    ) -> Result<RedemptionData, RedemptionError> {
        // Parse public keys
        let issuer_pubkey = parse_pubkey(&request.issuer_pubkey)?;
        let recipient_pubkey = parse_pubkey(&request.recipient_pubkey)?;

        // Lookup the note
        let note = self
            .tracker
            .lookup_note(&issuer_pubkey, &recipient_pubkey)
            .map_err(|_| RedemptionError::NoteNotFound)?;

        // Verify note signature
        note.verify_signature(&issuer_pubkey)
            .map_err(|_| RedemptionError::InvalidNoteSignature)?;

        // Verify the AVL proof that the note exists in the tracker's tree.
        // This ensures the note is committed to the current on-chain state.
        let avl_root_digest = self.tracker.get_state().avl_root_digest;
        let avl_proof = self
            .tracker
            .generate_proof(&issuer_pubkey, &recipient_pubkey)
            .map_err(|e| {
                RedemptionError::StorageError(format!("Proof generation failed: {:?}", e))
            })?;

        let proof_valid = self.verify_redemption_proof(
            &avl_proof.avl_proof,
            &note,
            &issuer_pubkey,
            &avl_root_digest,
        )?;

        if !proof_valid {
            return Err(RedemptionError::StorageError(
                "AVL proof verification failed: note not found in tracker state".to_string(),
            ));
        }

        // Check if there's sufficient outstanding debt to redeem
        if note.outstanding_debt() < request.amount {
            return Err(RedemptionError::InsufficientCollateral(
                note.outstanding_debt(),
                request.amount,
            ));
        }

        // Note: Time lock validation is handled by the ErgoScript contract (basis.es).
        // Normal redemption requires valid signatures (no time restriction).
        // Emergency redemption requires (HEIGHT - trackerCreationHeight) > 2160.
        // The transaction builder and manager do NOT enforce time locks.

        // Build redemption transaction using the transaction builder directly
        // The reserve_box_id should already be set in the request from the API layer
        let redemption_data =
            build_redemption_transaction(&mut self.tracker, &note, &avl_proof, request)?;

        Ok(redemption_data)
    }

    /// Build unsigned redemption transaction data for blockchain integration
    ///
    /// This method prepares the complete unsigned redemption transaction structure by:
    /// 1. Validating the redemption request parameters
    /// 2. Preparing transaction components (inputs, outputs, data inputs)
    /// 3. Assembling context extension with contract parameters
    /// 4. Creating transaction data structure ready for signing
    ///
    /// The resulting transaction follows the Basis contract specification:
    /// - Spends the reserve box to redeem collateral
    /// - Uses tracker box as data input for AVL proof verification
    /// - Creates updated reserve box with reduced collateral
    /// - Sends redeemed funds to recipient address
    /// - Includes Schnorr signatures and AVL proofs
    ///
    /// When blockchain integration is complete, this will produce actual
    /// Ergo transactions that can be submitted to the network.
    pub fn build_unsigned_redemption_transaction(
        &mut self,
        note: &IouNote,
        proof: &crate::NoteProof,
        request: &RedemptionRequest,
        reserve_box_id: &str,
        tracker_box_id: &str,
        tracker_nft_id: &str,
        issuer_sig: &[u8],
        tracker_sig: &[u8],
        context: &TxContext,
        reserve_box_value: u64,
    ) -> Result<RedemptionData, RedemptionError> {
        // Generate real proofs using tracker state
        let issuer_pubkey_bytes = parse_pubkey(&request.issuer_pubkey).map_err(|e| {
            RedemptionError::TransactionError(format!("Invalid issuer pubkey: {}", e))
        })?;
        let recipient_pubkey_bytes = parse_pubkey(&request.recipient_pubkey).map_err(|e| {
            RedemptionError::TransactionError(format!("Invalid recipient pubkey: {}", e))
        })?;

        // Generate reserve lookup proof FIRST (before inserting, for old state)
        // For first redemption, this will return None proof
        let reserve_lookup_proof = self
            .tracker
            .generate_reserve_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
            .map_err(|e| {
                RedemptionError::TransactionError(format!(
                    "Failed to generate reserve lookup proof: {:?}",
                    e
                ))
            })?;

        // Generate reserve insert proof (for inserting redeemed amount into reserve tree)
        // This also updates the reserve AVL tree and returns the updated tree digest for R5
        let new_already_redeemed = note.amount_redeemed + request.amount;
        let (reserve_insert_proof, updated_reserve_tree) = self
            .tracker
            .generate_reserve_insert_proof(
                &issuer_pubkey_bytes,
                &recipient_pubkey_bytes,
                note.timestamp,
                new_already_redeemed,
            )
            .map_err(|e| {
                RedemptionError::TransactionError(format!(
                    "Failed to generate reserve insert proof: {:?}",
                    e
                ))
            })?;

        // Generate tracker lookup proof (for totalDebt)
        let tracker_lookup_proof = self
            .tracker
            .generate_tracker_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
            .map_err(|e| {
                RedemptionError::TransactionError(format!(
                    "Failed to generate tracker lookup proof: {:?}",
                    e
                ))
            })?;

        let mut transaction_data =
            RedemptionTransactionBuilder::build_unsigned_redemption_transaction(
                reserve_box_id,
                tracker_box_id,
                tracker_nft_id,
                note,
                &request.recipient_address,
                &reserve_insert_proof,
                issuer_sig,
                tracker_sig,
                &issuer_pubkey_bytes,
                context,
                reserve_box_value,
                reserve_lookup_proof.proof,
                tracker_lookup_proof.proof,
                request.amount,
            )
            .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

        // Set the updated reserve tree for R5 register
        transaction_data.updated_reserve_tree = Some(updated_reserve_tree);

        // Generate unique redemption ID for tracking
        let redemption_id = format!(
            "redeem_{}_{}_{}",
            &request.issuer_pubkey[..16],
            &request.recipient_pubkey[..16],
            note.timestamp
        );

        // Create transaction bytes using real transaction builder
        let transaction_bytes =
            RedemptionTransactionBuilder::build_redemption_transaction(&transaction_data)
                .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

        // Required signatures: issuer and tracker
        let required_signatures = vec![
            request.issuer_pubkey.clone(),
            "tracker_signature_key".to_string(), // Placeholder - in real implementation, this would be tracker's pubkey
        ];

        // Use configured fee
        let estimated_fee = context.fee;

        // Redemption can happen immediately since we checked the time lock
        let redemption_time = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64;

        Ok(RedemptionData {
            redemption_id,
            note: note.clone(),
            avl_proof: proof.avl_proof.clone(),
            transaction_bytes: hex::encode(transaction_bytes),
            required_signatures,
            estimated_fee,
            redemption_time,
        })
    }

    /// Complete redemption by updating the note with redeemed amount
    pub fn complete_redemption(
        &mut self,
        issuer_pubkey: &PubKey,
        recipient_pubkey: &PubKey,
        redeemed_amount: u64,
    ) -> Result<(), RedemptionError> {
        // Get the current note
        let mut note = self
            .tracker
            .lookup_note(issuer_pubkey, recipient_pubkey)
            .map_err(|_| RedemptionError::NoteNotFound)?;

        // Update the redeemed amount
        note.amount_redeemed += redeemed_amount;

        // Update the timestamp to ensure it's newer than the existing one
        note.timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_err(|_| RedemptionError::StorageError("Failed to get current time".to_string()))?
            .as_millis() as u64;

        // Update the note in tracker
        self.tracker
            .update_note(issuer_pubkey, &note)
            .map_err(RedemptionError::from)
    }

    /// Verify redemption proof against on-chain state
    ///
    /// This verifies:
    /// 1. The note signature (Schnorr signature from issuer)
    /// 2. The AVL proof that the note exists in the tracker's AVL tree
    ///
    /// # Arguments
    /// * `proof` - The AVL proof bytes for the note lookup
    /// * `note` - The IOU note being redeemed
    /// * `issuer_pubkey` - The issuer's public key (33 bytes compressed secp256k1)
    /// * `avl_root_digest` - The expected AVL tree root digest (33 bytes) from on-chain state
    ///
    /// # Returns
    /// `true` if both the signature and AVL proof are valid, `false` otherwise
    pub fn verify_redemption_proof(
        &self,
        proof: &[u8],
        note: &IouNote,
        issuer_pubkey: &PubKey,
        avl_root_digest: &[u8; 33],
    ) -> Result<bool, RedemptionError> {
        // Step 1: Verify the note signature (Schnorr signature from issuer)
        note.verify_signature(issuer_pubkey)
            .map_err(|_| RedemptionError::InvalidNoteSignature)?;

        // Step 2: Verify the AVL proof that the note exists in the tracker's tree
        // The key is blake2b256(issuer_pubkey || recipient_pubkey)
        let mut key_data = Vec::with_capacity(66);
        key_data.extend_from_slice(issuer_pubkey);
        key_data.extend_from_slice(&note.recipient_pubkey);
        let key = blake2b256_hash(&key_data);

        // The value is total_debt (amount_collected - amount_redeemed) as 8-byte big-endian
        let total_debt = note.outstanding_debt();
        let value = total_debt.to_be_bytes().to_vec();

        let avl_valid =
            basis_trees::BasisAvlTree::verify_proof(avl_root_digest, proof, &key, &value);

        if !avl_valid {
            return Ok(false);
        }

        Ok(true)
    }
}

/// Parse hex-encoded public key
fn parse_pubkey(hex_str: &str) -> Result<PubKey, RedemptionError> {
    let bytes = hex::decode(hex_str)
        .map_err(|_| RedemptionError::InvalidPublicKey("Invalid hex encoding".to_string()))?;

    bytes
        .try_into()
        .map_err(|_| RedemptionError::InvalidPublicKey("Must be 33 bytes".to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::IouNote;

    #[test]
    fn test_redemption_validation() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let redemption_manager = RedemptionManager::new(tracker);

        // Test public key parsing
        let valid_pubkey = "02".to_string() + &"0".repeat(64); // 33 bytes hex
        let parsed = parse_pubkey(&valid_pubkey);
        assert!(parsed.is_ok());

        // Test invalid hex
        let invalid_hex = "zz".to_string();
        let parsed = parse_pubkey(&invalid_hex);
        assert!(parsed.is_err());

        // Test wrong length
        let wrong_length = "02".to_string() + &"0".repeat(62); // 32 bytes
        let parsed = parse_pubkey(&wrong_length);
        assert!(parsed.is_err());
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_invalid_issuer_pubkey() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        // Create a valid note first
        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65], // dummy signature
        };

        let request = RedemptionRequest {
            issuer_pubkey: "invalid_hex".to_string(),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 1000,
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(matches!(err, RedemptionError::TransactionError(_)));
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_invalid_recipient_pubkey() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: "invalid_hex".to_string(),
            amount: 1000,
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(matches!(err, RedemptionError::TransactionError(_)));
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_empty_reserve_box_id() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 1000,
            timestamp: 1672531200,
            reserve_box_id: "".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        // Empty reserve box ID should be rejected
        assert!(result.is_err());
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_empty_tracker_box_id() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 1000,
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        // Empty tracker box ID should be rejected
        assert!(result.is_err());
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_invalid_issuer_signature_length() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 1000,
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(64), // 64 bytes instead of 65
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        // Invalid issuer signature length should be rejected
        assert!(result.is_err());
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_zero_amount() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 0, // Zero amount
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        // Zero amount should be rejected
        assert!(result.is_err());
    }

    #[test]
    fn test_build_unsigned_redemption_transaction_excessive_amount() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let mut redemption_manager = RedemptionManager::new(tracker);

        let issuer_secret = secp256k1::SecretKey::from_slice(&[1u8; 32]).unwrap();
        let secp = secp256k1::Secp256k1::new();
        let issuer_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &issuer_secret);
        let issuer_pubkey_bytes = issuer_pubkey.serialize();

        let recipient_secret = secp256k1::SecretKey::from_slice(&[2u8; 32]).unwrap();
        let recipient_pubkey = secp256k1::PublicKey::from_secret_key(&secp, &recipient_secret);
        let recipient_pubkey_bytes = recipient_pubkey.serialize();

        let note = IouNote {
            recipient_pubkey: recipient_pubkey_bytes,
            amount_collected: 10000,
            amount_redeemed: 0,
            timestamp: 1672531200,
            signature: [0u8; 65],
        };

        let request = RedemptionRequest {
            issuer_pubkey: hex::encode(&issuer_pubkey_bytes),
            recipient_pubkey: hex::encode(&recipient_pubkey_bytes),
            amount: 20000, // Exceeds outstanding debt
            timestamp: 1672531200,
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51),
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
            reserve_box_value: 20000000, // 0.02 ERG reserve box value
            fee_input_box_ids: Vec::new(),
            fee_input_total_value: 0,
        };

        let proof = crate::NoteProof {
            note: note.clone(),
            avl_proof: vec![],
            operations: vec![],
        };

        let result = redemption_manager.build_unsigned_redemption_transaction(
            &note,
            &proof,
            &request,
            "box123",
            "tracker123",
            "nft123",
            &[0u8; 65],
            &[0u8; 65],
            &TxContext {
                current_height: 1000,
                fee: 1000000,
                change_address: "9".repeat(51),
                network_prefix: 0,
            },
            20000000, // Reserve box value: enough to cover redemption + fee
        );

        // Excessive amount should be rejected
        assert!(result.is_err());
    }
}

// Helper function to build redemption transaction using the transaction builder
fn build_redemption_transaction(
    tracker: &mut TrackerStateManager,
    note: &IouNote,
    proof: &crate::NoteProof,
    request: &RedemptionRequest,
) -> Result<RedemptionData, RedemptionError> {
    // In a real implementation, this would:
    // 1. Fetch the reserve box from the blockchain
    // 2. Create the redemption transaction following the contract logic
    // 3. Include the AVL proof and signatures
    // 4. Calculate appropriate fees

    // For now, create a mock transaction structure using the unified builder
    let redemption_id = format!(
        "redeem_{}_{}_{}",
        &request.issuer_pubkey[..16],
        &request.recipient_pubkey[..16],
        note.timestamp
    );

    // Use blockchain data from request (fetched by API layer)
    let actual_tracker_box_id = request.tracker_box_id.clone();
    let actual_tracker_nft_id = request.tracker_nft_id.clone();
    let current_height = request.current_height as u32; // Convert u64 to u32 for transaction builder

    // Decode issuer signature from hex
    let issuer_signature_bytes = hex::decode(&request.issuer_signature).map_err(|e| {
        RedemptionError::TransactionError(format!("Invalid issuer signature hex: {}", e))
    })?;

    if issuer_signature_bytes.len() != 65 {
        return Err(RedemptionError::TransactionError(format!(
            "Issuer signature must be 65 bytes, got {}",
            issuer_signature_bytes.len()
        )));
    }

    // Get tracker signature from request or generate placeholder for emergency
    let tracker_signature_bytes = if request.emergency {
        // Emergency redemption - tracker signature not required by contract after 3 days
        // Use a dummy signature (contract will bypass verification based on HEIGHT)
        vec![0u8; 65]
    } else if let Some(ref tracker_sig_hex) = request.tracker_signature {
        // Normal redemption with tracker signature provided
        hex::decode(tracker_sig_hex).map_err(|e| {
            RedemptionError::TransactionError(format!("Invalid tracker signature hex: {}", e))
        })?
    } else {
        // Normal redemption without tracker signature - this should not happen in production
        // The API layer should have provided the tracker signature
        return Err(RedemptionError::TransactionError(
            "Tracker signature required for normal redemption".to_string(),
        ));
    };

    if tracker_signature_bytes.len() != 65 && !request.emergency {
        return Err(RedemptionError::TransactionError(format!(
            "Tracker signature must be 65 bytes, got {}",
            tracker_signature_bytes.len()
        )));
    }

    // Use the unified transaction builder with provided values
    // First, get reserve lookup proof from tracker state
    // Parse public keys for reserve lookup proof generation
    let issuer_pubkey_bytes = parse_pubkey(&request.issuer_pubkey)
        .map_err(|e| RedemptionError::TransactionError(format!("Invalid issuer pubkey: {}", e)))?;
    let recipient_pubkey_bytes = parse_pubkey(&request.recipient_pubkey).map_err(|e| {
        RedemptionError::TransactionError(format!("Invalid recipient pubkey: {}", e))
    })?;

    // Generate reserve lookup proof FIRST (before inserting, for old state)
    // For first redemption, this will return None proof
    let reserve_lookup_proof = tracker
        .generate_reserve_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
        .map_err(|e| {
            RedemptionError::TransactionError(format!(
                "Failed to generate reserve lookup proof: {:?}",
                e
            ))
        })?;

    // Generate reserve insert proof (for inserting redeemed amount into reserve tree)
    // This also updates the reserve AVL tree and returns the updated tree digest for R5
    let new_already_redeemed = note.amount_redeemed + request.amount;
    let (reserve_insert_proof, updated_reserve_tree) = tracker
        .generate_reserve_insert_proof(
            &issuer_pubkey_bytes,
            &recipient_pubkey_bytes,
            note.timestamp,
            new_already_redeemed,
        )
        .map_err(|e| {
            RedemptionError::TransactionError(format!(
                "Failed to generate reserve insert proof: {:?}",
                e
            ))
        })?;

    // Generate tracker lookup proof (for totalDebt)
    let tracker_lookup_proof = tracker
        .generate_tracker_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
        .map_err(|e| {
            RedemptionError::TransactionError(format!(
                "Failed to generate tracker lookup proof: {:?}",
                e
            ))
        })?;

    // Convert proofs to bytes for transaction builder
    let reserve_lookup_proof_bytes: Option<Vec<u8>> = reserve_lookup_proof.proof;
    let tracker_lookup_proof_bytes: Vec<u8> = tracker_lookup_proof.proof;

    // Pass proofs to transaction builder
    let mut transaction_data = RedemptionTransactionBuilder::build_unsigned_redemption_transaction(
        &request.reserve_box_id,
        &actual_tracker_box_id,
        &actual_tracker_nft_id,
        note,
        &request.recipient_address,
        &reserve_insert_proof,
        &issuer_signature_bytes,
        &tracker_signature_bytes,
        &issuer_pubkey_bytes,
        &TxContext {
            current_height,
            fee: 1000000, // 0.001 ERG fee from config
            change_address: request.change_address.clone(),
            network_prefix: 0,
        },
        request.reserve_box_value, // Use actual reserve box value from blockchain
        reserve_lookup_proof_bytes,
        tracker_lookup_proof_bytes,
        request.amount,
    )
    .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

    // Set the updated reserve tree for R5 register
    transaction_data.updated_reserve_tree = Some(updated_reserve_tree);

    // Add fee inputs. If the request provides them, use those; otherwise use a
    // placeholder so offline/tests can still build a balanced transaction.
    let required_fee = transaction_data.fee;
    if !request.fee_input_box_ids.is_empty() {
        transaction_data.fee_input_box_ids = request.fee_input_box_ids.clone();
        transaction_data.fee_input_total_value = request.fee_input_total_value;
        transaction_data.change_address = Some(request.change_address.clone());
    } else {
        transaction_data.fee_input_box_ids = vec!["test_fee_input_placeholder".to_string()];
        transaction_data.fee_input_total_value = required_fee;
        transaction_data.change_address = Some(request.change_address.clone());
    }

    // Use real transaction builder to create the actual transaction bytes
    let transaction_bytes =
        RedemptionTransactionBuilder::build_redemption_transaction(&transaction_data)
            .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

    // Required signatures: issuer and tracker
    // Note: Tracker pubkey should be fetched from tracker configuration
    let required_signatures = vec![
        request.issuer_pubkey.clone(),
        "tracker_pubkey_required".to_string(),
    ];

    // Estimated fee (0.001 ERG)
    let estimated_fee = 1000000;

    // Redemption time is recorded for tracking purposes
    // Note: Time lock validation is handled by the ErgoScript contract
    let redemption_time = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64;

    Ok(RedemptionData {
        redemption_id,
        note: note.clone(),
        avl_proof: proof.avl_proof.clone(),
        transaction_bytes: hex::encode(transaction_bytes),
        required_signatures,
        estimated_fee,
        redemption_time,
    })
}
