//! Redemption flow for Basis offchain notes

use thiserror::Error;

use crate::{IouNote, NoteError, PubKey, TrackerStateManager};
use crate::transaction_builder::{RedemptionTransactionBuilder, TxContext};

#[derive(Error, Debug)]
pub enum RedemptionError {
    #[error("Note not found")]
    NoteNotFound,
    #[error("Invalid note signature")]
    InvalidNoteSignature,
    #[error("Redemption too early: {0} < {1}")]
    RedemptionTooEarly(u64, u64),
    #[error("Insufficient collateral: {0} < {1}")]
    InsufficientCollateral(u64, u64),
    #[error("Reserve not found: {0}")]
    ReserveNotFound(String),
    #[error("Transaction building error: {0}")]
    TransactionError(String),
    #[error("Storage error: {0}")]
    StorageError(String),
    #[error("Invalid public key: {0}")]
    InvalidPublicKey(String),
}

impl From<NoteError> for RedemptionError {
    fn from(err: NoteError) -> Self {
        match err {
            NoteError::InvalidSignature => RedemptionError::InvalidNoteSignature,
            NoteError::FutureTimestamp => RedemptionError::StorageError("Future timestamp".to_string()),
            NoteError::PastTimestamp => RedemptionError::StorageError("Past timestamp".to_string()),
            NoteError::RedemptionTooEarly => RedemptionError::RedemptionTooEarly(0, 0),
            NoteError::StorageError(msg) => RedemptionError::StorageError(msg),
            _ => RedemptionError::StorageError(format!("{:?}", err)),
        }
    }
}

/// Redemption request parameters
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RedemptionRequest {
    /// Issuer's public key (hex encoded)
    pub issuer_pubkey: String,
    /// Recipient's public key (hex encoded)
    pub recipient_pubkey: String,
    /// Amount to redeem
    pub amount: u64,
    /// Timestamp of the note being redeemed
    pub timestamp: u64,
    /// Reserve contract box ID (hex encoded)
    pub reserve_box_id: String,
    /// Tracker box ID (hex encoded) - fetched from blockchain
    pub tracker_box_id: String,
    /// Tracker NFT ID from reserve box R6 register (hex encoded, 64 chars = 32 bytes)
    pub tracker_nft_id: String,
    /// Current blockchain height - fetched from Ergo node
    pub current_height: u64,  // Stored as u64 from API, converted to u32 for transaction builder
    /// Recipient's address for redemption output
    pub recipient_address: String,
    /// Change address for transaction outputs (derived from tracker pubkey if not specified)
    pub change_address: String,
    /// Issuer's Schnorr signature (65 bytes, hex encoded = 130 chars)
    /// Signs: key || totalDebt [|| 0L for emergency]
    /// where key = blake2b256(ownerKey || receiverKey)
    pub issuer_signature: String,
    /// Whether this is an emergency redemption (after 3 days tracker unavailability)
    #[serde(default)]
    pub emergency: bool,
    /// Tracker's Schnorr signature (65 bytes, hex encoded = 130 chars)
    /// Optional: will be generated by server if not provided for normal redemption
    #[serde(default)]
    pub tracker_signature: Option<String>,
}

/// Redemption proof and transaction data
#[derive(Debug, Clone)]
pub struct RedemptionData {
    /// Unique redemption ID
    pub redemption_id: String,
    /// The note being redeemed
    pub note: IouNote,
    /// AVL tree proof for the note
    pub avl_proof: Vec<u8>,
    /// Redemption transaction bytes (hex encoded)
    pub transaction_bytes: String,
    /// Required signatures for the transaction
    pub required_signatures: Vec<String>,
    /// Estimated transaction fee
    pub estimated_fee: u64,
    /// Timestamp when redemption can be executed
    pub redemption_time: u64,
}

/// Redemption manager for handling note redemptions
pub struct RedemptionManager {
    pub tracker: TrackerStateManager,
}

impl RedemptionManager {
    /// Create a new redemption manager
    pub fn new(tracker: TrackerStateManager) -> Self {
        Self { tracker }
    }

    /// Initiate redemption process for a note
    pub fn initiate_redemption(
        &mut self,
        request: &RedemptionRequest,
    ) -> Result<RedemptionData, RedemptionError> {
        // Parse public keys
        let issuer_pubkey = parse_pubkey(&request.issuer_pubkey)?;
        let recipient_pubkey = parse_pubkey(&request.recipient_pubkey)?;

        // Lookup the note
        let note = self
            .tracker
            .lookup_note(&issuer_pubkey, &recipient_pubkey)
            .map_err(|_| RedemptionError::NoteNotFound)?;

        // Verify note signature
        note.verify_signature(&issuer_pubkey)
            .map_err(|_| RedemptionError::InvalidNoteSignature)?;

        // Check if there's sufficient outstanding debt to redeem
        if note.outstanding_debt() < request.amount {
            return Err(RedemptionError::InsufficientCollateral(
                note.outstanding_debt(),
                request.amount,
            ));
        }

        // Check redemption time lock (for testing, reduce from 1 week to 1 minute)
        let current_time = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let min_redemption_time = note.timestamp + 60; // 60 seconds (1 minute) for testing
        if current_time < min_redemption_time {
            return Err(RedemptionError::RedemptionTooEarly(
                current_time,
                min_redemption_time,
            ));
        }

        // Generate proof for the note
        let proof = self
            .tracker
            .generate_proof(&issuer_pubkey, &recipient_pubkey)?;

        // Build redemption transaction using the transaction builder directly
        // The reserve_box_id should already be set in the request from the API layer
        let redemption_data = build_redemption_transaction(&mut self.tracker, &note, &proof, request)?;

        Ok(redemption_data)
    }

    /// Build unsigned redemption transaction data for blockchain integration
    ///
    /// This method prepares the complete unsigned redemption transaction structure by:
    /// 1. Validating the redemption request parameters
    /// 2. Preparing transaction components (inputs, outputs, data inputs)
    /// 3. Assembling context extension with contract parameters
    /// 4. Creating transaction data structure ready for signing
    ///
    /// The resulting transaction follows the Basis contract specification:
    /// - Spends the reserve box to redeem collateral
    /// - Uses tracker box as data input for AVL proof verification
    /// - Creates updated reserve box with reduced collateral
    /// - Sends redeemed funds to recipient address
    /// - Includes Schnorr signatures and AVL proofs
    ///
    /// When blockchain integration is complete, this will produce actual
    /// Ergo transactions that can be submitted to the network.
    pub fn build_unsigned_redemption_transaction(
        &self,
        note: &IouNote,
        proof: &crate::NoteProof,
        request: &RedemptionRequest,
        reserve_box_id: &str,
        tracker_box_id: &str,
        tracker_nft_id: &str,
        issuer_sig: &[u8],
        tracker_sig: &[u8],
        context: &TxContext,
    ) -> Result<RedemptionData, RedemptionError> {
        // For this helper function, we don't have access to tracker state
        // so we pass empty proofs
        // The caller should use the main initiate_redemption function for full functionality
        let transaction_data = RedemptionTransactionBuilder::build_unsigned_redemption_transaction(
            reserve_box_id,
            tracker_box_id,
            tracker_nft_id,
            note,
            &request.recipient_address,
            &proof.avl_proof,
            issuer_sig,
            tracker_sig,
            context,
            None, // reserve_lookup_proof - not available in this context
            vec![0u8; 64], // tracker_lookup_proof - placeholder
        ).map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

        // Generate unique redemption ID for tracking
        let redemption_id = format!(
            "redeem_{}_{}_{}",
            &request.issuer_pubkey[..16],
            &request.recipient_pubkey[..16],
            note.timestamp
        );

        // Create transaction bytes using ergo-lib integration
        // This uses the real transaction builder that validates all parameters
        let transaction_bytes = RedemptionTransactionBuilder::build_redemption_transaction(
            &transaction_data.reserve_box_id,
            &transaction_data.tracker_box_id,
            &transaction_data.tracker_nft_id,
            &transaction_data.recipient_address,
            transaction_data.redemption_amount,
            transaction_data.fee,
            context.current_height,
        )
        .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

        // Required signatures: issuer and tracker
        let required_signatures = vec![
            request.issuer_pubkey.clone(),
            "tracker_signature_key".to_string(), // Placeholder - in real implementation, this would be tracker's pubkey
        ];

        // Use configured fee
        let estimated_fee = context.fee;

        // Redemption can happen immediately since we checked the time lock
        let redemption_time = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        Ok(RedemptionData {
            redemption_id,
            note: note.clone(),
            avl_proof: proof.avl_proof.clone(),
            transaction_bytes: hex::encode(transaction_bytes),
            required_signatures,
            estimated_fee,
            redemption_time,
        })
    }

    /// Complete redemption by updating the note with redeemed amount
    pub fn complete_redemption(
        &mut self,
        issuer_pubkey: &PubKey,
        recipient_pubkey: &PubKey,
        redeemed_amount: u64,
    ) -> Result<(), RedemptionError> {
        // Get the current note
        let mut note = self
            .tracker
            .lookup_note(issuer_pubkey, recipient_pubkey)
            .map_err(|_| RedemptionError::NoteNotFound)?;

        // Update the redeemed amount
        note.amount_redeemed += redeemed_amount;

        // Update the timestamp to ensure it's newer than the existing one
        note.timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_err(|_| RedemptionError::StorageError("Failed to get current time".to_string()))?
            .as_secs();

        // Update the note in tracker
        self.tracker
            .update_note(issuer_pubkey, &note)
            .map_err(RedemptionError::from)
    }

    /// Verify redemption proof against on-chain state
    pub fn verify_redemption_proof(
        &self,
        _proof: &[u8],
        note: &IouNote,
        issuer_pubkey: &PubKey,
    ) -> Result<bool, RedemptionError> {
        // In a real implementation, this would verify the AVL proof against
        // the on-chain commitment stored in the reserve contract

        // For now, just verify the note signature
        note.verify_signature(issuer_pubkey)
            .map(|_| true)
            .map_err(|_| RedemptionError::InvalidNoteSignature)
    }
}

/// Parse hex-encoded public key
fn parse_pubkey(hex_str: &str) -> Result<PubKey, RedemptionError> {
    let bytes = hex::decode(hex_str)
        .map_err(|_| RedemptionError::InvalidPublicKey("Invalid hex encoding".to_string()))?;

    bytes
        .try_into()
        .map_err(|_| RedemptionError::InvalidPublicKey("Must be 33 bytes".to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::IouNote;

    #[test]
    fn test_redemption_validation() {
        let mut tracker = TrackerStateManager::new_with_temp_storage();
        let redemption_manager = RedemptionManager::new(tracker);

        // Test public key parsing
        let valid_pubkey = "02".to_string() + &"0".repeat(64); // 33 bytes hex
        let parsed = parse_pubkey(&valid_pubkey);
        assert!(parsed.is_ok());

        // Test invalid hex
        let invalid_hex = "zz".to_string();
        let parsed = parse_pubkey(&invalid_hex);
        assert!(parsed.is_err());

        // Test wrong length
        let wrong_length = "02".to_string() + &"0".repeat(62); // 32 bytes
        let parsed = parse_pubkey(&wrong_length);
        assert!(parsed.is_err());
    }

    #[test]
    fn test_redemption_request_validation() {
        let request = RedemptionRequest {
            issuer_pubkey: "02".to_string() + &"0".repeat(64),
            recipient_pubkey: "02".to_string() + &"1".repeat(64),
            amount: 1000,
            timestamp: 1672531200, // Jan 1, 2023
            reserve_box_id: "box123".to_string(),
            tracker_box_id: "tracker123".to_string(),
            tracker_nft_id: "nft123".to_string(),
            current_height: 1000,
            recipient_address: "9".repeat(51), // Ergo address format
            change_address: "9".repeat(51),
            issuer_signature: "01".repeat(65),
            emergency: false,
            tracker_signature: Some("02".repeat(65)),
        };

        // Should parse valid public keys
        let issuer = parse_pubkey(&request.issuer_pubkey);
        let recipient = parse_pubkey(&request.recipient_pubkey);
        assert!(issuer.is_ok());
        assert!(recipient.is_ok());
    }
}

// Helper function to build redemption transaction using the transaction builder
fn build_redemption_transaction(
    tracker: &mut TrackerStateManager,
    note: &IouNote,
    proof: &crate::NoteProof,
    request: &RedemptionRequest,
) -> Result<RedemptionData, RedemptionError> {
    // In a real implementation, this would:
    // 1. Fetch the reserve box from the blockchain
    // 2. Create the redemption transaction following the contract logic
    // 3. Include the AVL proof and signatures
    // 4. Calculate appropriate fees

    // For now, create a mock transaction structure using the unified builder
    let redemption_id = format!(
        "redeem_{}_{}_{}",
        &request.issuer_pubkey[..16],
        &request.recipient_pubkey[..16],
        note.timestamp
    );

    // Use blockchain data from request (fetched by API layer)
    let actual_tracker_box_id = request.tracker_box_id.clone();
    let actual_tracker_nft_id = request.tracker_nft_id.clone();
    let current_height = request.current_height as u32; // Convert u64 to u32 for transaction builder

    // Decode issuer signature from hex
    let issuer_signature_bytes = hex::decode(&request.issuer_signature)
        .map_err(|e| RedemptionError::TransactionError(format!("Invalid issuer signature hex: {}", e)))?;
    
    if issuer_signature_bytes.len() != 65 {
        return Err(RedemptionError::TransactionError(
            format!("Issuer signature must be 65 bytes, got {}", issuer_signature_bytes.len())
        ));
    }

    // Get tracker signature from request or generate placeholder for emergency
    let tracker_signature_bytes = if request.emergency {
        // Emergency redemption - tracker signature not required by contract after 3 days
        // Use a dummy signature (contract will bypass verification based on HEIGHT)
        vec![0u8; 65]
    } else if let Some(ref tracker_sig_hex) = request.tracker_signature {
        // Normal redemption with tracker signature provided
        hex::decode(tracker_sig_hex)
            .map_err(|e| RedemptionError::TransactionError(format!("Invalid tracker signature hex: {}", e)))?
    } else {
        // Normal redemption without tracker signature - this should not happen in production
        // The API layer should have provided the tracker signature
        return Err(RedemptionError::TransactionError(
            "Tracker signature required for normal redemption".to_string()
        ));
    };

    if tracker_signature_bytes.len() != 65 && !request.emergency {
        return Err(RedemptionError::TransactionError(
            format!("Tracker signature must be 65 bytes, got {}", tracker_signature_bytes.len())
        ));
    }

    // Use the unified transaction builder with provided values
    // First, get reserve lookup proof from tracker state
    // Parse public keys for reserve lookup proof generation
    let issuer_pubkey_bytes = parse_pubkey(&request.issuer_pubkey)
        .map_err(|e| RedemptionError::TransactionError(format!("Invalid issuer pubkey: {}", e)))?;
    let recipient_pubkey_bytes = parse_pubkey(&request.recipient_pubkey)
        .map_err(|e| RedemptionError::TransactionError(format!("Invalid recipient pubkey: {}", e)))?;
    
    // Generate reserve lookup proof (for already_redeemed)
    let reserve_lookup_proof = tracker.generate_reserve_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
        .map_err(|e| RedemptionError::TransactionError(format!("Failed to generate reserve lookup proof: {:?}", e)))?;
    
    // Generate tracker lookup proof (for totalDebt)
    let tracker_lookup_proof = tracker.generate_tracker_lookup_proof(&issuer_pubkey_bytes, &recipient_pubkey_bytes)
        .map_err(|e| RedemptionError::TransactionError(format!("Failed to generate tracker lookup proof: {:?}", e)))?;
    
    // Convert proofs to bytes for transaction builder
    let reserve_lookup_proof_bytes: Option<Vec<u8>> = reserve_lookup_proof.proof;
    let tracker_lookup_proof_bytes: Vec<u8> = tracker_lookup_proof.proof;
    
    // Pass proofs to transaction builder
    let transaction_data = RedemptionTransactionBuilder::build_unsigned_redemption_transaction(
        &request.reserve_box_id,
        &actual_tracker_box_id,
        &actual_tracker_nft_id,
        note,
        &request.recipient_address,
        &proof.avl_proof,
        &issuer_signature_bytes,
        &tracker_signature_bytes,
        &TxContext {
            current_height,
            fee: 1000000, // 0.001 ERG fee from config
            change_address: request.change_address.clone(),
            network_prefix: 0,
        },
        reserve_lookup_proof_bytes,
        tracker_lookup_proof_bytes,
    ).map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

    // Use real ergo-lib transaction builder from basis_store to create the actual transaction bytes
    let transaction_bytes = RedemptionTransactionBuilder::build_redemption_transaction(
        &transaction_data.reserve_box_id,
        &transaction_data.tracker_box_id,
        &transaction_data.tracker_nft_id,
        &request.recipient_address,
        transaction_data.redemption_amount,
        transaction_data.fee,
        current_height,
    )
    .map_err(|e| RedemptionError::TransactionError(e.to_string()))?;

    // Required signatures: issuer and tracker
    let required_signatures = vec![
        request.issuer_pubkey.clone(),
        "tracker_signature_key".to_string(), // Placeholder for tracker signature
    ];

    // Estimated fee (0.001 ERG)
    let estimated_fee = 1000000;

    // Redemption can happen immediately since we checked the time lock
    let redemption_time = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();

    Ok(RedemptionData {
        redemption_id,
        note: note.clone(),
        avl_proof: proof.avl_proof.clone(),
        transaction_bytes: hex::encode(transaction_bytes),
        required_signatures,
        estimated_fee,
        redemption_time,
    })
}