[package]
name = "basis_cli"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[features]
default = []
bin = []

# Test dependencies
[dev-dependencies]
basis_store = { path = "../basis_store" }

[[bin]]
name = "basis_cli"
path = "src/main.rs"
required-features = ["bin"]