[package]
name = "basis_store"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[lib]
name = "basis_store"
path = "src/lib.rs"

[dependencies]
ergo_avltree_rust = { workspace = true }
fjall = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.10.0"
hex = "0.4"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt", "macros", "rt-multi-thread"] }