package basis.contracts

import basis.offchain.SigUtils
import com.google.common.primitives.Longs
import scorex.crypto.encode.Base16
import scorex.crypto.hash.Blake2b256
import sigma.serialization.{GroupElementSerializer, ValueSerializer}
import sigma.ast.GroupElementConstant
import work.lithos.plasma.PlasmaParameters
import work.lithos.plasma.collections.PlasmaMap
import sigma.data.AvlTreeFlags

/**
 * Generates test vectors for cross-validation with the Rust Basis tracker implementation.
 *
 * Run with:
 *   sbt "runMain basis.contracts.TestVectorGenerator"
 *
 * The output can be copied into the Rust test files (crates/basis_store/src/schnorr_test_vectors.rs
 * and crates/basis_store/src/scala_test_vectors.rs) when regenerating reference vectors.
 */
object TestVectorGenerator extends App {

  import SigUtils._

  val g = BasisConstants.g

  val alicePubKey = ParticipantKeys.alicePublicKey
  val bobPubKey = ParticipantKeys.bobPublicKey
  val trackerPubKey = ParticipantKeys.trackerPublicKey
  val aliceSecret = ParticipantKeys.aliceSecret
  val trackerSecret = ParticipantKeys.trackerSecret

  val alicePubKeyHex = Base16.encode(alicePubKey.getEncoded.toArray)
  val bobPubKeyHex = Base16.encode(bobPubKey.getEncoded.toArray)
  val trackerPubKeyHex = Base16.encode(trackerPubKey.getEncoded.toArray)

  def buildMessage(ownerKey: sigma.GroupElement, receiverKey: sigma.GroupElement, totalDebt: Long, timestamp: Long): Array[Byte] = {
    val key = Blake2b256(ownerKey.getEncoded.toArray ++ receiverKey.getEncoded.toArray)
    key ++ Longs.toByteArray(totalDebt) ++ Longs.toByteArray(timestamp)
  }

  def vectorHeader(): Unit = {
    println("// Generated by basis.contracts.TestVectorGenerator")
    println("// Alice pubkey: " + alicePubKeyHex)
    println("// Bob pubkey:   " + bobPubKeyHex)
    println("// Tracker pubkey: " + trackerPubKeyHex)
    println()
  }

  def formatSchnorrVector(
    id: String,
    desc: String,
    issuer: sigma.GroupElement,
    recipient: sigma.GroupElement,
    amount: Long,
    timestamp: Long,
    secret: BigInt,
    shouldVerify: Boolean
  ): String = {
    val msg = buildMessage(issuer, recipient, amount, timestamp)
    val (a, z) = if (secret == BigInt(0)) {
      (g.exp(BigInt(0).bigInteger), BigInt(0))
    } else {
      SigUtils.sign(msg, secret)
    }
    val sigBytes = a.getEncoded.toArray ++ z.toByteArray.padTo(32, 0.toByte)
    val issuerHex = Base16.encode(issuer.getEncoded.toArray)
    val recipientHex = Base16.encode(recipient.getEncoded.toArray)
    val amountStr = if (amount < 0) "18446744073709551615u64" else amount + "u64"
    val timestampStr = if (timestamp < 0) "18446744073709551615u64" else timestamp + "u64"

    "  SchnorrTestVector {\n" +
    "    id: \"" + id + "\",\n" +
    "    description: \"" + desc + "\",\n" +
    "    issuer_pubkey_hex: \"" + issuerHex + "\",\n" +
    "    recipient_pubkey_hex: \"" + recipientHex + "\",\n" +
    "    amount: " + amountStr + ",\n" +
    "    timestamp: " + timestampStr + ",\n" +
    "    message_hex: \"" + Base16.encode(msg) + "\",\n" +
    "    signature_hex: \"" + Base16.encode(sigBytes) + "\",\n" +
    "    should_verify: " + shouldVerify + ",\n" +
    "  },"
  }

  def printSchnorrVectors(): Unit = {
    println("// Schnorr signature test vectors")
    println("pub const SCHNORR_TEST_VECTORS: &[SchnorrTestVector] = &[")

    val cases = Seq(
      ("TV001", "Standard valid signature", alicePubKey, bobPubKey, 1000000000L, 1743379200000L, aliceSecret, true),
      ("TV002", "All-zero signature should fail", alicePubKey, bobPubKey, 1000000000L, 1743379200000L, BigInt(0), false),
      ("TV003", "Valid tracker signature", trackerPubKey, bobPubKey, 500000000L, 1743379201000L, trackerSecret, true),
      ("TV009", "Maximum u64 values", alicePubKey, bobPubKey, -1L, -1L, aliceSecret, true),
      ("TV010", "Zero amount and timestamp", alicePubKey, bobPubKey, 0L, 0L, aliceSecret, true)
    )

    for (c <- cases) {
      println(formatSchnorrVector(c._1, c._2, c._3, c._4, c._5, c._6, c._7, c._8))
    }

    println("];")
    println()
  }

  def printSerializedConstants(): Unit = {
    println("// Serialized Ergo constants")
    println("pub const ACTION_BYTE_SERIALIZED: &str = \"" + Base16.encode(ValueSerializer.serialize(0.toByte)) + "\";")
    println("pub const TOTAL_DEBT_SERIALIZED: &str = \"" + Base16.encode(ValueSerializer.serialize(50000000L)) + "\";")
    println("pub const TIMESTAMP_SERIALIZED: &str = \"" + Base16.encode(ValueSerializer.serialize(1743379200000L)) + "\";")
    println("pub const ALICE_PUBKEY_SERIALIZED: &str = \"" + Base16.encode(ValueSerializer.serialize(GroupElementConstant(alicePubKey))) + "\";")
    println("pub const BOB_PUBKEY_SERIALIZED: &str = \"" + Base16.encode(ValueSerializer.serialize(GroupElementConstant(bobPubKey))) + "\";")
    println()
  }

  def printAvlVectors(): Unit = {
    println("// AVL tree test vectors")

    val params = PlasmaParameters(32, None)
    val trackerMap = new PlasmaMap[Array[Byte], Array[Byte]](AvlTreeFlags.InsertOnly, params)
    val reserveMap = new PlasmaMap[Array[Byte], Array[Byte]](AvlTreeFlags(insertAllowed = true, updateAllowed = true, removeAllowed = false), params)

    val key1 = Blake2b256(alicePubKey.getEncoded.toArray ++ bobPubKey.getEncoded.toArray)
    val totalDebt1 = Longs.toByteArray(50000000L)
    trackerMap.insert((key1, totalDebt1))
    val trackerTree = trackerMap.ergoValue.getValue
    val trackerProof = trackerMap.lookUp(key1).proof.bytes

    println("pub const TRACKER_AVL_VECTORS: &[AvlTestVector] = &[")
    println("  AvlTestVector {")
    println("    id: \"AVL_T001\",")
    println("    description: \"Tracker tree with single debt entry (50M nanoERG)\",")
    println("    key_hex: \"" + Base16.encode(key1) + "\",")
    println("    value_hex: \"" + Base16.encode(totalDebt1) + "\",")
    println("    proof_hex: \"" + Base16.encode(trackerProof) + "\",")
    println("    root_digest_hex: \"" + Base16.encode(trackerTree.digest.toArray) + "\",")
    println("    tree_type: \"tracker\",")
    println("  },")
    println("];")
    println()

    val timestamp = 1743379200000L
    val redeemed = 25000000L
    val reserveValue = Longs.toByteArray(timestamp) ++ Longs.toByteArray(redeemed)
    reserveMap.insert((key1, reserveValue))
    val reserveTree = reserveMap.ergoValue.getValue
    val reserveProof = reserveMap.lookUp(key1).proof.bytes

    println("pub const RESERVE_AVL_VECTORS: &[AvlTestVector] = &[")
    println("  AvlTestVector {")
    println("    id: \"AVL_R001\",")
    println("    description: \"Reserve tree with first redemption (timestamp=" + timestamp + ", redeemed=" + redeemed + ")\",")
    println("    key_hex: \"" + Base16.encode(key1) + "\",")
    println("    value_hex: \"" + Base16.encode(reserveValue) + "\",")
    println("    proof_hex: \"" + Base16.encode(reserveProof) + "\",")
    println("    root_digest_hex: \"" + Base16.encode(reserveTree.digest.toArray) + "\",")
    println("    tree_type: \"reserve\",")
    println("  },")
    println("];")
    println()
  }

  vectorHeader()
  printSchnorrVectors()
  printSerializedConstants()
  printAvlVectors()
}
